# mongodb://my_user:my_password@127.0.0.1:27017/my_db
SCIELO_CORE_ID_PROVIDER_DB_URI = (
    os.getenv("SCIELO_CORE_ID_PROVIDER_DB_URI") or
    "mongodb://127.0.0.1:27017/my_id_provider"
)
SCIELO_CORE_WEBSITE_DB_URI = (
    os.getenv("SCIELO_CORE_WEBSITE_DB_URI") or
    "mongodb://127.0.0.1:27017/my_website"
)

SCIELO_CORE_ID_PROVIDER_CELERY_BROKER_URL = os.getenv(
    "SCIELO_CORE_ID_PROVIDER_CELERY_BROKER_URL", 'amqp://guest@0.0.0.0:5672//')
SCIELO_CORE_ID_PROVIDER_CELERY_RESULT_BACKEND_URL = os.getenv(
    "SCIELO_CORE_ID_PROVIDER_CELERY_RESULT_BACKEND_URL", 'rpc://')

SCIELO_CORE_MIGRATION_CELERY_BROKER_URL = os.getenv(
    "SCIELO_CORE_MIGRATION_CELERY_BROKER_URL", 'amqp://guest@0.0.0.0:5672//')
SCIELO_CORE_MIGRATION_CELERY_RESULT_BACKEND_URL = os.getenv(
    "SCIELO_CORE_MIGRATION_CELERY_RESULT_BACKEND_URL", 'rpc://')

SCIELO_CORE_CONCURRENT_PROCESSING = os.getenv(
    'SCIELO_CORE_CONCURRENT_PROCESSING') or False


SCIELO_CORE_REGISTER_MIGRATION_QUEUE = (
    os.getenv("SCIELO_CORE_REGISTER_MIGRATION_QUEUE") or 'migr_default')
SCIELO_CORE_HARVEST_XMLS_QUEUE = (
    os.getenv("SCIELO_CORE_HARVEST_XMLS_QUEUE") or 'migr_high_priority')
SCIELO_CORE_MIGRATE_XMLS_QUEUE = (
    os.getenv("SCIELO_CORE_MIGRATE_XMLS_QUEUE") or 'migr_high_priority')
SCIELO_CORE_UNDO_ID_REQUEST_QUEUE = (
    os.getenv("SCIELO_CORE_UNDO_ID_REQUEST_QUEUE") or 'migr_high_priority')

SCIELO_CORE_MIGRATION_LOGFILE = os.getenv(
    'SCIELO_CORE_MIGRATION_LOGFILE') or 'migration.log'
SCIELO_CORE_ID_PROVIDER_LOGFILE = os.getenv(
    'SCIELO_CORE_ID_PROVIDER_LOGFILE') or 'id_provider.log'