FLASK_ENV=development
FLASK_APP=scielocore.app:create_app
SECRET_KEY=changeme
DATABASE_URI=sqlite:///scielocore.db
CELERY_BROKER_URL=amqp://guest:guest@localhost/
CELERY_RESULT_BACKEND_URL=rpc://

# DATABASE_URI=sqlite:///scielocore.db
# DATABASE_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
DATABASE_URI=postgres://localhost:5432/scielocore

# CELERY_BROKER_URL=amqp://guest:guest@localhost/
# CELERY_RESULT_BACKEND_URL=rpc://

CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
CELERY_RESULT_BACKEND_URL=redis://redis

SCIELO_CORE_ID_PROVIDER_DB_URI=mongodb://127.0.0.1:27017/my_id_provider
SCIELO_CORE_WEBSITE_DB_URI=mongodb://127.0.0.1:27017/my_website
SCIELO_CORE_ID_PROVIDER_CELERY_BROKER_URL=amqp://guest@0.0.0.0:5672//
SCIELO_CORE_ID_PROVIDER_CELERY_RESULT_BACKEND_URL=rpc://

SCIELO_CORE_MIGRATION_CELERY_BROKER_URL=amqp://guest@0.0.0.0:5672//
SCIELO_CORE_MIGRATION_CELERY_RESULT_BACKEND_URL=rpc://
SCIELO_CORE_CONCURRENT_PROCESSING=true


SCIELO_CORE_REGISTER_MIGRATION_QUEUE=migr_default
SCIELO_CORE_HARVEST_XMLS_QUEUE=migr_high_priority
SCIELO_CORE_MIGRATE_XMLS_QUEUE=migr_high_priority
SCIELO_CORE_UNDO_ID_REQUEST_QUEUE=migr_high_priority

SCIELO_CORE_MIGRATION_LOGFILE=migration.log
SCIELO_CORE_ID_PROVIDER_LOGFILE=id_provider.log